[project]
name = "epidoc_conversion"
dynamic = ["version"]

dependencies = ["betacode", "hooktest>=1.3.1", "lxml", "setuptools>=80.4.0"]

requires-python = ">= 3.11"

[dependency-groups]
dev = ["pytest>=8.4.0"]
