ENTITIES = {
    '&Acirc;': 'Â',
    '&Amacr;': 'Ā',
    # I don't know if Unicode can actually represent this -- it should have the turnstile on top of the A
    '&Arpress;': 'ⱵA',
    '&Ebreve;': 'Ĕ',
    # this is an approximation
    '&Eunc;': 'ϵ',
    '&Ndot;': 'Ṅ',
    '&Obreve;': 'Ŏ',
    '&Omacr;': 'Ō',
    '&abreve;': 'ă',
    '&acirc;': 'â',
    '&acutebreve;': '́̆',
    '&adot;': 'ȧ',
    '&amacr;': 'ā',
    '&anceps;': '×',
    '&ast;': '*',
    '&brevemacr;': '᷋',
    '&cacute;': 'ć',
    '&cbreve;': 'c̆',
    '&ccaron;': 'č',
    '&ccedil;': 'ç',
    '&cnull;': 'c̥',
    '&dash;': '–',
    '&eacute;': 'é',
    '&ebreve;': 'ĕ',
    '&ecaron;': 'ě',
    '&ecirc;': 'ê',
    '&edot;': 'ė',
    # just an approximation
    '&eglide;': 'ε̬',
    '&egrave;': 'è',
    '&emacr;': 'ē',
    '&emacracute;': 'ḗ',
    '&enull;': 'ε̥',
    '&euml;': 'ë',
    '&gacute;': 'ǵ',
    '&gdot;': 'ġ',
    '&grave;': '`',
    '&ibreve;': 'ĭ',
    '&icirc;': 'î',
    # this is the closest unicode can get to ι with a glide below
    '&iglide;': 'ɩ̧',
    '&imacr;': 'ī',
    '&kacute;': 'ḱ',
    # I'm guessing they meant '&koppa;'
    '&koopa;': 'ϙ',
    '&koppa;': 'ϟ',
    '&lins;': '<img src="//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Greek_Lambda_Athenian.svg/13px-Greek_Lambda_Athenian.svg.png" decoding="async" width="13" height="16" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/27/Greek_Lambda_Athenian.svg/19px-Greek_Lambda_Athenian.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/27/Greek_Lambda_Athenian.svg/26px-Greek_Lambda_Athenian.svg.png 2x" data-file-width="43" data-file-height="53"/>',
    '&hellip;': '…',
    '&ldquo;': '“',
    '&lnull;': 'λ̥',
    '&lpress;': '⊣',
    '&rdquo;': '”',
    '&macracute;': '́̄',
    '&macrbreve;': '᷋',
    '&macrdot;': '∸',
    '&mdash;': '—',
    '&mnull;': 'μ̥',
    '&ndash;': '–',
    '&ndot;': 'ṅ',
    '&nbsp;': ' ',
    '&nnull;': 'ν̥',
    '&nring;': 'n̥',
    '&num;': 'ʹ',
    '&obreve;': 'ŏ',
    '&ocirc;': 'ô',
    '&odblac;': 'ö',
    '&omacr;': 'ō',
    '&ouml;': 'ö',
    '&lpar;': '(',
    '&rpar;': ')',
    '&rpress;': 'Ⱶ',
    '&lsqb;': '[',
    '&rsqb;': ']',
    '&lsquo;': '‘',
    '&rsquo;': '’',
    '&rmacr;': 'ṝ',
    '&rnull;': 'ρ̥',
    '&root;': '√',
    '&sampi;': 'ϡ',
    '&tnull;': 't̥',
    '&tnum;': '͵',
    '&rcirc;': 'ř',
    # not quote right, but about as close as we can get
    '&rlcrop;': '⎣',
    '&rough;': '῾',
    '&rtilde;': 'r̃',
    '&sacute;': 'ś',
    '&sbreve;': 'š',
    '&schwa;': 'ə',
    '&scirc;': 'ŝ',
    '&scron;': 'š',
    '&smooth;': '᾽',
    # not quote right, but about as close as we can get
    '&ubreve;': 'ŭ',
    '&ucirc;': 'û',
    # this is the closest unicode can currently get to υ with a glide
    '&uglide;': 'ṵ',
    '&umacr;': 'ū',
    '&uuml;': 'ü',
    '&ulcrop;': '⎤',
    '&urcrop;': '⎡',
    '&ymacr;': 'ȳ',
    '&zcaron;': 'ž',
}